# Generated by Django 6.0.3 on 2026-03-18 15:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalline',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Computed tax amount', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='tax_base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Amount subject to tax', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Tax rate applied (percentage)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
